alter table if exists ACCOUNT
    drop constraint if exists FK9rxadd7hdlmarov6qbvaot0po;
alter table if exists ACCOUNT
    drop constraint if exists FK4cfkq2sywnlcu6fxm9xbrmsjs;
alter table if exists CITY
    drop constraint if exists FKg20pyto8we1mjpxdf0ixmfkgd;
alter table if exists CITY
    drop constraint if exists FKi4i6u7b4qdx3pjr1j6qq6y2vm;
alter table if exists STATION
    drop constraint if exists FKanu16qi926w9omslreoj7smq1;
alter table if exists STATION
    drop constraint if exists FKp7x70rdqw4fidaslc492bnfgk;
alter table if exists STATION
    drop constraint if exists FKl8s21emvhb86aubh7m389hrlo;
drop table if exists ACCOUNT cascade;
drop table if exists CITY cascade;
drop table if exists STATION cascade;
create table ACCOUNT
(
    ID          int8 generated by default as identity,
    CREATED_DT  timestamp not null,
    MODIFIED_DT timestamp,
    CREATED_BY  int8,
    MODIFIED_BY int8,
    primary key (ID)
);
create table CITY
(
    ID          int8 generated by default as identity,
    CREATED_DT  timestamp   not null,
    MODIFIED_DT timestamp,
    DISTRICT    varchar(32) not null,
    NAME        varchar(32) not null,
    REGION      varchar(32) not null,
    CREATED_BY  int8,
    MODIFIED_BY int8,
    primary key (ID)
);
create table STATION
(
    ID             int8 generated by default as identity,
    CREATED_DT     timestamp    not null,
    MODIFIED_DT    timestamp,
    APARTMENT      varchar(16),
    STREET         varchar(10),
    ZIP_CODE       varchar(10),
    x              float8,
    y              float8,
    TRANSPORT_TYPE varchar(255) not null,
    CREATED_BY     int8,
    MODIFIED_BY    int8,
    CITY_ID        int8,
    primary key (ID)
);
alter table if exists ACCOUNT
    add constraint FK9rxadd7hdlmarov6qbvaot0po foreign key (CREATED_BY) references ACCOUNT;
alter table if exists ACCOUNT
    add constraint FK4cfkq2sywnlcu6fxm9xbrmsjs foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists CITY
    add constraint FKg20pyto8we1mjpxdf0ixmfkgd foreign key (CREATED_BY) references ACCOUNT;
alter table if exists CITY
    add constraint FKi4i6u7b4qdx3pjr1j6qq6y2vm foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists STATION
    add constraint FKanu16qi926w9omslreoj7smq1 foreign key (CREATED_BY) references ACCOUNT;
alter table if exists STATION
    add constraint FKp7x70rdqw4fidaslc492bnfgk foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists STATION
    add constraint FKl8s21emvhb86aubh7m389hrlo foreign key (CITY_ID) references CITY;
alter table if exists ACCOUNT
    drop constraint if exists FK9rxadd7hdlmarov6qbvaot0po;
alter table if exists ACCOUNT
    drop constraint if exists FK4cfkq2sywnlcu6fxm9xbrmsjs;
alter table if exists CITY
    drop constraint if exists FKg20pyto8we1mjpxdf0ixmfkgd;
alter table if exists CITY
    drop constraint if exists FKi4i6u7b4qdx3pjr1j6qq6y2vm;
alter table if exists STATION
    drop constraint if exists FKanu16qi926w9omslreoj7smq1;
alter table if exists STATION
    drop constraint if exists FKp7x70rdqw4fidaslc492bnfgk;
alter table if exists STATION
    drop constraint if exists FKl8s21emvhb86aubh7m389hrlo;
drop table if exists ACCOUNT cascade;
drop table if exists CITY cascade;
drop table if exists STATION cascade;
create table ACCOUNT
(
    ID          int8 generated by default as identity,
    CREATED_DT  timestamp not null,
    MODIFIED_DT timestamp,
    CREATED_BY  int8,
    MODIFIED_BY int8,
    primary key (ID)
);
create table CITY
(
    ID          int8 generated by default as identity,
    CREATED_DT  timestamp   not null,
    MODIFIED_DT timestamp,
    DISTRICT    varchar(32) not null,
    NAME        varchar(32) not null,
    REGION      varchar(32) not null,
    CREATED_BY  int8,
    MODIFIED_BY int8,
    primary key (ID)
);
create table STATION
(
    ID             int8 generated by default as identity,
    CREATED_DT     timestamp    not null,
    MODIFIED_DT    timestamp,
    APARTMENT      varchar(16),
    STREET         varchar(10),
    ZIP_CODE       varchar(10),
    x              float8,
    y              float8,
    TRANSPORT_TYPE varchar(255) not null,
    CREATED_BY     int8,
    MODIFIED_BY    int8,
    CITY_ID        int8,
    primary key (ID)
);
alter table if exists ACCOUNT
    add constraint FK9rxadd7hdlmarov6qbvaot0po foreign key (CREATED_BY) references ACCOUNT;
alter table if exists ACCOUNT
    add constraint FK4cfkq2sywnlcu6fxm9xbrmsjs foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists CITY
    add constraint FKg20pyto8we1mjpxdf0ixmfkgd foreign key (CREATED_BY) references ACCOUNT;
alter table if exists CITY
    add constraint FKi4i6u7b4qdx3pjr1j6qq6y2vm foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists STATION
    add constraint FKanu16qi926w9omslreoj7smq1 foreign key (CREATED_BY) references ACCOUNT;
alter table if exists STATION
    add constraint FKp7x70rdqw4fidaslc492bnfgk foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists STATION
    add constraint FKl8s21emvhb86aubh7m389hrlo foreign key (CITY_ID) references CITY;
